version: '3.8'

services:
  db:
    image: postgis/postgis:17-3.5
    container_name: django_postgis_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - .initdb:/docker-entrypoint-initdb.d
    networks:
      - django_network

  web: 
    build: .
    container_name: django_web
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - django_network
volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge
